// Re-export all shared types for convenience
export type {
  StructuredResume,
  ResumeSection,
  SectionContent,
  FileType,
  SectionType,
  ContentType,
  SourceReference,
  ContentMetadata,
  ChangeRecommendation,
  ChangeType,
  ConfidenceLevel,
  ATSImpactLevel,
  ChangeCategory,
  ChangeStatus,
  ATSAnalysisResult,
  OptimizationResult,
  WeakBulletPoint,
  DuplicateSkill,
  KeywordOpportunity,
  ApiResponse,
  UploadResumeResponse,
  AnalyzeResumeRequest,
  AnalyzeResumeResponse,
  ApplyChangesRequest,
  ApplyChangesResponse,
  ChangeDecision,
  ChatMessage,
  ChatMessageType,
  OptimizationMode,
  GetHtmlResponse,
  ManualEdit,
  ManualEditRequest,
  ManualEditResponse,
  ChatEditRequest,
  ChatEditResponse,
} from '@resume-optimizer/shared';
